import { Vendor, RiskAssessment } from "./types";

export const vendors: Vendor[] = [
  {
    id: "v001",
    name: "Acme Cloud Services",
    category: "Technology",
    contactName: "Sarah Johnson",
    contactEmail: "sarah.johnson@acmecloud.com",
    contactPhone: "+1 (555) 234-5678",
    website: "https://acmecloud.com",
    address: "123 Tech Park, Suite 400",
    country: "United States",
    status: "active",
    riskLevel: "low",
    onboardedAt: "2023-01-15",
    contractExpiry: "2026-01-14",
    annualSpend: 480000,
    description: "Primary cloud infrastructure and SaaS solutions provider.",
    tags: ["cloud", "infrastructure", "saas"],
    compliance: [
      {
        id: "c001",
        name: "SOC 2 Type II",
        status: "compliant",
        dueDate: "2025-12-31",
        notes: "Certificate renewed annually.",
      },
      {
        id: "c002",
        name: "ISO 27001",
        status: "compliant",
        dueDate: "2025-09-30",
        notes: "Last audit passed with zero findings.",
      },
      {
        id: "c003",
        name: "GDPR Assessment",
        status: "pending",
        dueDate: "2025-08-31",
        notes: "Annual review in progress.",
      },
    ],
  },
  {
    id: "v002",
    name: "GlobalPay Solutions",
    category: "Financial Services",
    contactName: "Michael Chen",
    contactEmail: "m.chen@globalpay.io",
    contactPhone: "+1 (555) 987-6543",
    website: "https://globalpay.io",
    address: "88 Finance Avenue",
    country: "United States",
    status: "active",
    riskLevel: "medium",
    onboardedAt: "2022-06-01",
    contractExpiry: "2025-05-31",
    annualSpend: 1200000,
    description: "Payment processing and financial transaction management.",
    tags: ["payments", "fintech", "processing"],
    compliance: [
      {
        id: "c004",
        name: "PCI DSS",
        status: "compliant",
        dueDate: "2025-11-30",
        notes: "Level 1 certified service provider.",
      },
      {
        id: "c005",
        name: "AML Policy Review",
        status: "non_compliant",
        dueDate: "2025-07-15",
        notes: "Remediation plan submitted, awaiting approval.",
      },
    ],
  },
  {
    id: "v003",
    name: "SecureLogix Ltd",
    category: "Cybersecurity",
    contactName: "Priya Kapoor",
    contactEmail: "p.kapoor@securelogix.com",
    contactPhone: "+44 20 7946 0958",
    website: "https://securelogix.com",
    address: "12 Cyber Lane, Canary Wharf",
    country: "United Kingdom",
    status: "under_review",
    riskLevel: "high",
    onboardedAt: "2021-11-20",
    contractExpiry: "2025-11-19",
    annualSpend: 360000,
    description: "Managed security services and penetration testing.",
    tags: ["security", "pentest", "soc"],
    compliance: [
      {
        id: "c006",
        name: "Cyber Essentials Plus",
        status: "compliant",
        dueDate: "2025-10-01",
        notes: "Certified.",
      },
      {
        id: "c007",
        name: "Data Processing Agreement",
        status: "non_compliant",
        dueDate: "2025-06-30",
        notes: "DPA requires update for new GDPR amendments.",
      },
      {
        id: "c008",
        name: "Annual Security Audit",
        status: "pending",
        dueDate: "2025-09-15",
        notes: "Scheduled for Q3.",
      },
    ],
  },
  {
    id: "v004",
    name: "OfficeSupply Pro",
    category: "Office Supplies",
    contactName: "Tom Williams",
    contactEmail: "tom@officesupplypro.com",
    contactPhone: "+1 (555) 321-9876",
    website: "https://officesupplypro.com",
    address: "456 Commerce Blvd",
    country: "United States",
    status: "active",
    riskLevel: "low",
    onboardedAt: "2023-03-10",
    contractExpiry: "2026-03-09",
    annualSpend: 45000,
    description: "Office supplies and stationery procurement.",
    tags: ["supplies", "procurement"],
    compliance: [
      {
        id: "c009",
        name: "Vendor Code of Conduct",
        status: "compliant",
        dueDate: "2025-12-31",
        notes: "Signed and acknowledged.",
      },
    ],
  },
  {
    id: "v005",
    name: "DataInsight Analytics",
    category: "Data & Analytics",
    contactName: "Elena Rossi",
    contactEmail: "e.rossi@datainsight.eu",
    contactPhone: "+39 02 1234 5678",
    website: "https://datainsight.eu",
    address: "Via Tecnica 22, Milan",
    country: "Italy",
    status: "inactive",
    riskLevel: "medium",
    onboardedAt: "2020-08-05",
    contractExpiry: "2024-08-04",
    annualSpend: 150000,
    description: "Business intelligence and analytics platform provider.",
    tags: ["analytics", "bi", "data"],
    compliance: [
      {
        id: "c010",
        name: "GDPR Assessment",
        status: "not_applicable",
        dueDate: "2024-08-04",
        notes: "Contract expired.",
      },
    ],
  },
  {
    id: "v006",
    name: "BuildFast Construction",
    category: "Facilities",
    contactName: "James Park",
    contactEmail: "j.park@buildfast.co",
    contactPhone: "+1 (555) 654-3210",
    website: "https://buildfast.co",
    address: "789 Industrial Road",
    country: "United States",
    status: "terminated",
    riskLevel: "critical",
    onboardedAt: "2019-04-01",
    contractExpiry: "2023-03-31",
    annualSpend: 0,
    description: "Office renovation and facilities management — contract terminated.",
    tags: ["facilities", "construction"],
    compliance: [
      {
        id: "c011",
        name: "Health & Safety Certificate",
        status: "non_compliant",
        dueDate: "2023-01-01",
        notes: "Multiple violations led to contract termination.",
      },
    ],
  },
];

export const riskAssessments: RiskAssessment[] = [
  {
    vendorId: "v001",
    assessedAt: "2025-06-10",
    assessedBy: "Alice Brown",
    overallRisk: "low",
    financialRisk: "low",
    operationalRisk: "low",
    reputationalRisk: "low",
    cyberSecurityRisk: "medium",
    notes: "Vendor demonstrates strong governance and controls.",
  },
  {
    vendorId: "v002",
    assessedAt: "2025-05-20",
    assessedBy: "Alice Brown",
    overallRisk: "medium",
    financialRisk: "medium",
    operationalRisk: "low",
    reputationalRisk: "low",
    cyberSecurityRisk: "medium",
    notes: "AML non-compliance requires monitoring.",
  },
  {
    vendorId: "v003",
    assessedAt: "2025-06-01",
    assessedBy: "David Nguyen",
    overallRisk: "high",
    financialRisk: "low",
    operationalRisk: "high",
    reputationalRisk: "high",
    cyberSecurityRisk: "medium",
    notes: "Under review pending DPA remediation.",
  },
];

export function getVendorById(id: string): Vendor | undefined {
  return vendors.find((v) => v.id === id);
}

export function getRiskAssessmentByVendorId(vendorId: string): RiskAssessment | undefined {
  return riskAssessments.find((r) => r.vendorId === vendorId);
}
